version: '3.7'

networks: 
  dockersql-network:
    driver: bridge

services: 
  isys.services.api:
    image: isys.services.api
    build:
      context: "./Backend/"
      dockerfile: DockerfileApi
    container_name: isys.services.api
    networks:
      - dockersql-network
    restart: always
    depends_on:
      - sqlserver
    environment:  
      - ASPNETCORE_ENVIRONMENT=Development  
    ports:
      - "8000:80"
      - "8001:443"
  sqlserver:
    image: sqlserver
    hostname: 'sqlserver'  
    build:
      "./Backend/db"
    container_name: sqlserver
    networks:
      - dockersql-network
    restart: always
    ports: 
      - "1433:1433"