version: '3.7'
services: 
  api:
    image: api
    build:
      context: "./Backend/"
      dockerfile: DockerfileApi
    container_name: ContainerApi
    restart: always
    depends_on:
      - sqlserver
    ports:
      - "8001:80"
  sqlserver:
    image: sqlserver
    build:
      "./Backend/db"
    container_name: ContainerSqlServer
    restart: always
    ports: 
      - "1433:1433"